### ISSUE TITLE
Cookie issue in CatalogSync

### ISSUE THREAD

**Issue by haydenmc** [Purdue-io/PurdueApi#30]
CatalogSync is failing with a brand spankin' new error

```
[09/17/2019 20:30:13 > 52f9ad: SYS INFO] Status changed to Initializing
[09/17/2019 20:30:13 > 52f9ad: SYS INFO] Run script 'CatalogSync.exe' with script host - 'WindowsScriptHost'
[09/17/2019 20:30:13 > 52f9ad: SYS INFO] Status changed to Running
[09/17/2019 20:30:18 > 52f9ad: ERR ] 
[09/17/2019 20:30:18 > 52f9ad: ERR ] Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Net.CookieException: The 'Value'='MDAwSEhIMTA5NjQwMQ==;' part of the cookie is invalid.
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Net.Cookie.VerifySetDefaults(CookieVariant variant, Uri uri, Boolean isLocalDomain, String localDomain, Boolean set_default, Boolean isThrow)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Net.CookieContainer.Add(Cookie cookie)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at CatalogApi.CatalogConnection.<Request>d__d.MoveNext() in c:\projects\purdueapi-375\CatalogApi\CatalogConnection.cs:line 176
[09/17/2019 20:30:18 > 52f9ad: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at CatalogApi.CatalogConnection.<Request>d__d.MoveNext() in c:\projects\purdueapi-375\CatalogApi\CatalogConnection.cs:line 186
[09/17/2019 20:30:18 > 52f9ad: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at CatalogApi.CatalogConnection.<Request>d__d.MoveNext() in c:\projects\purdueapi-375\CatalogApi\CatalogConnection.cs:line 186
[09/17/2019 20:30:18 > 52f9ad: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at CatalogApi.CatalogConnection.<Request>d__d.MoveNext() in c:\projects\purdueapi-375\CatalogApi\CatalogConnection.cs:line 186
[09/17/2019 20:30:18 > 52f9ad: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at CatalogApi.CatalogConnection.<Request>d__d.MoveNext() in c:\projects\purdueapi-375\CatalogApi\CatalogConnection.cs:line 186
[09/17/2019 20:30:18 > 52f9ad: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at CatalogApi.CatalogConnection.<Authenticate>d__1.MoveNext() in c:\projects\purdueapi-375\CatalogApi\CatalogConnection.cs:line 95
[09/17/2019 20:30:18 > 52f9ad: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at CatalogApi.CatalogApi.<Authenticate>d__0.MoveNext() in c:\projects\purdueapi-375\CatalogApi\CatalogApi.cs:line 65
[09/17/2019 20:30:18 > 52f9ad: ERR ]    --- End of inner exception stack trace ---
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at System.Threading.Tasks.Task`1.get_Result()
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at CatalogSync.Program..ctor(String user, String pass) in c:\projects\purdueapi-375\CatalogSync\Program.cs:line 32
[09/17/2019 20:30:18 > 52f9ad: ERR ]    at CatalogSync.Program.Main() in c:\projects\purdueapi-375\CatalogSync\Program.cs:line 24
[09/17/2019 20:30:18 > 52f9ad: SYS INFO] Status changed to Failed
[09/17/2019 20:30:18 > 52f9ad: SYS ERR ] Job failed due to exit code -532462766
```

**Comment by haydenmc** [comment]
Fixed, CatalogSync is running on production instance now.
